# Generated by Django 4.2.23 on 2025-07-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("querydb", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="liked_book",
            new_name="liked_books",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
