# Generated by Django 4.2.23 on 2025-07-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="url",
        ),
        migrations.AddField(
            model_name="article",
            name="pdf_url",
            field=models.URLField(blank=True, null=True, verbose_name="PDF_URL"),
        ),
    ]
