# Generated by Django 4.2.23 on 2025-07-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_remove_article_url_article_pdf_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
        migrations.RemoveField(
            model_name="note",
            name="text",
        ),
        migrations.AddField(
            model_name="note",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="article",
            name="pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("highlight", "Highlight"),
                            ("underline", "Underline"),
                        ],
                        max_length=20,
                    ),
                ),
                ("page", models.IntegerField()),
                ("left", models.FloatField()),
                ("top", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="notes.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="note",
            name="annotation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="notes.annotation",
            ),
        ),
    ]
