# Generated by Django 4.2.23 on 2025-07-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_remove_article_content_remove_note_text_note_body_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotation",
            old_name="left",
            new_name="x",
        ),
        migrations.RenameField(
            model_name="annotation",
            old_name="top",
            new_name="y",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="body",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="annotation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="note",
            name="article",
        ),
        migrations.RemoveField(
            model_name="note",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="annotation",
            name="annotation_type",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notes.article"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pdf_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="annotation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notes.annotation",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
