# Generated by Django 4.2.23 on 2025-07-13 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_rename_left_annotation_x_rename_top_annotation_y_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotation",
            old_name="x",
            new_name="left",
        ),
        migrations.RenameField(
            model_name="annotation",
            old_name="y",
            new_name="top",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="content",
            new_name="body",
        ),
        migrations.AddField(
            model_name="annotation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="article",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.article",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="annotation",
            name="annotation_type",
            field=models.CharField(
                choices=[("highlight", "Highlight"), ("underline", "Underline")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="notes.article",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="annotation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="notes.annotation",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
